config/routes.rb
Rails.application.routes.draw do
  root 'home#header'
  resources :categories do
    resources :products
  end
  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  get '/api' => redirect('/swagger/dist/index.html?url=/api-docs.json')
  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
  resources :users
  
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :items, class_name: 'OrderItem'
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    swagger_controller :order, 'Order'
    skip_before_action :verify_authenticity_token
  
    swagger_api :new do
    summary 'Returns orders'
    param :form, 'first_name', :string, :required, 'user first name'
    param :form, 'last_name', :string, :required, 'user last name'
  
    end
  
      def new
        respond_to do |format|
          @order = current_cart.order
          response = { :order => @order}
              format.html
              format.json { render json: response}
          end
      end
  
      def create
          @order = current_cart.order
  
          if @order.update(order_params.merge(status: 'open'))
              session[:cart_token] = nil
              redirect_to '/cart'
          else
              render :new
          end
      end
  
      private
  
      def order_params
          params.require(:order).permit(:first_name, :last_name)
      end
  
  
  end

app/views/orders/new.html.erb
<!DOCTYPE HTML>
<head>

  <meta charset="utf-8" />
  <style>
    body {

      font-family: Didot;
      text-align:center;
      margin: auto;
      background-color: lightblue;
        }
    .center {
      text-align:center;
      margin: auto;
      width: 50%;
    }
    .Powrót {
      text-align: right;
      margin-right: 15px;
    }
    h2 {
      font-size: 40px ;
    }

    a:link {
      text-decoration: none;
      color: black;
    }
    a:visited {
      color: black;
    }
    a:hover {
      color: #76767a;
    }
    </style>
    <body>
    <div class="Powrót"> <%= link_to "Powrót do koszyka  ", "/cart" %> </div>
<h2> Płatność </h2>

<%= form_for @order, url: checkout_path do |f| %>

    <div class="form-group">
        <%= f.label :first_name %>
        :
        <%= f.text_field :first_name %>
    </div>
    <br>
    <div class="form-group">
        <%= f.label :last_name %>
        :
        <%= f.text_field :last_name %>
    </div>
    <br>
    <%= f.submit 'Płatność' %>

<% end%>
</body>