config/routes.rb
Rails.application.routes.draw do
  root 'home#header'
  resources :categories do
    resources :products
  end
  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  get '/api' => redirect('/swagger/dist/index.html?url=/api-docs.json')
  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
  resources :users
  
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :product_categories
    has_many :products, through: :product_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    #swagger_controller :category, 'Categories'
    #swagger_api :index do
    #summary 'Returns categories'
    #end    gdy dodajemy swaggera, to wtedy json nam zwraca złe wartości 

    def index
        @categories = Category.order(:title)

        response = { :categories => @categories }
        
        respond_to do |format|
            format.html
            format.json { render json: response}
        end
    end
end

app/views/categories/index.html.erb
<!DOCTYPE HTML>
<head>
  <meta charset="utf-8" />
  <style>
  
    .Wyloguj {
      text-align: right;
      margin-right: 15px;
      }
    body {
      font-family: Didot;
      text-align:center;
      margin: auto;
      background-color: lightblue;
        }
    h2 {
      font-size: 40px ;
    }
    a:link {
      text-decoration: none;
      color: black;
    }
    a:visited {
      color: black;
    }
    a:hover {
      color: #76767a;
    }
    </style>
    <body>
    
    <div class="Wyloguj"> <%= link_to "Koszyk ", "/cart/items" %> &nbsp <%= link_to "Wyloguj", "/#" %> </div>
<h2> Kategorie  </h2>
<ul style="list-style: none;">
    <% @categories.each do |category|%>
        <li>
            <%= link_to category_products_path(category) do %>
            <%= category.title%>
            (<%= category.products.count %>) 
            <% end %>
        </li>
    <% end%>
        
</ul>
</body>