config/routes.rb
Rails.application.routes.draw do
  root 'home#header'
  resources :categories do
    resources :products
  end
  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  get '/api' => redirect('/swagger/dist/index.html?url=/api-docs.json')
  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'
  resources :users
  
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    validates :price, presence: true

    has_many :product_categories
    has_many :categories, through: :product_categories
    has_many :variants, class_name: 'ProductVariant'
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    swagger_controller :product, 'Products'
    
    swagger_api :index do
    summary 'Returns products'
    param :path, :category_id, :integer, :required, 'id'
    end
    def index
    end
    
        def index
            @category = Category.find(params[:category_id])
            @products = @category.products.includes(:variants).order(:title)
    
            response = { :category => @category, :products => @products }
    
            respond_to do |format|
                format.html
                format.json { render json: response}
            end
        end
    
    end

app/views/products/index.html.erb
<!DOCTYPE HTML>
<head>
  <meta charset="utf-8" />
  <style>
  .Powrót{
    text-align:right;
    margin-right: 15px;
    }
    body {
      font-family: Didot;
      text-align:center;
      margin: auto;
      background-color: lightblue;
        }
    h2 {
      font-size: 40px ;
    }
    a:link {
      text-decoration: none;
      color: black;
    }
    a:visited {
      color: black;
    }
    a:hover {
      color: #76767a;
    } 
</style>
</head>
<body>
<div class="Powrót"> <%= link_to "Powrót do kategorii  ", "/categories" %> </div>
<h2>
  <%= @category.title %> /
  Produkty
</h2>

<ul style="list-style: none;">
  <% @products.each do |product| %>
    <ul style="list-style: none;">
    <li>
      <%= product.title %> (<%= number_to_currency product.price %>)
      <%= form_tag order_items_path do %>
        <%= hidden_field_tag :product_id, product.id %>
        <%= number_field_tag :quantity, 1 %>
        <%= submit_tag "Dodaj do koszyka" %>
      <% end %>
    
    </li>
    </ul>
</ul>
<%end%>
</body>